name: Go

on:
  push:
    branches: [master, devel]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "stable"

      - uses: actions/checkout@v3

      - name: Build
        run: make build

      - name: Test
        run: make test
        env:
          PP_SECRET: ${{ secrets.PP_SECRET }}
          PP_CONSUMER_KEY: ${{ secrets.PP_CONSUMER_KEY }}
          PP_ACCESS_TOKEN: ${{ secrets.PP_ACCESS_TOKEN }}
